CREATE TABLE `mapregulator` (
	`mapId` INT(11) UNSIGNED NOT NULL,
	`dmgPercentage` FLOAT NOT NULL DEFAULT '100',
	`hpPercentage` FLOAT NOT NULL DEFAULT '100',
	`spelldmgPercentage` FLOAT NOT NULL DEFAULT '100',
	`note` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`mapId`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mobregulator` (
	`mobId` INT(11) UNSIGNED NOT NULL,
	`dmgPercentage` FLOAT NOT NULL DEFAULT '100',
	PRIMARY KEY (`mobId`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `spellregulator` (
	`spellId` INT(11) UNSIGNED NOT NULL,
	`percentage` FLOAT NOT NULL DEFAULT '100',
	PRIMARY KEY (`spellId`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `animationdata` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Name` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`WeaponFlags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BodyFlags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`FallbackAnimationID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BehaviourID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BehaviourTier` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `areagroup` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`AreaId1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`AreaId2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`AreaId3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`AreaId4` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`AreaId5` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`AreaId6` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`NextGroup` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `areatable` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Map` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`zone` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`exploreFlag` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`SoundPreferences` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`SoundPreferencesUnderwater` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`SoundAmbience` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ZoneMusic` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`zoneIntroMusic` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`area_level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Name1` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name2` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name3` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name4` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name5` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name6` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name7` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name8` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name9` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name10` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name11` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name12` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name13` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name14` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name15` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Name16` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`NameFlag` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`FactionGroup` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`LiquidType1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`LiquidType2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`LiquidType3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`LiquidType4` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`MinElevation` FLOAT NOT NULL DEFAULT '0',
	`AmbientMultiplier` FLOAT NOT NULL DEFAULT '0',
	`Light` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `charstartoutfit` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`gender` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`outfitId` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`itemId1` INT(11) NOT NULL DEFAULT '0',
	`itemId2` INT(11) NOT NULL DEFAULT '0',
	`itemId3` INT(11) NOT NULL DEFAULT '0',
	`itemId4` INT(11) NOT NULL DEFAULT '0',
	`itemId5` INT(11) NOT NULL DEFAULT '0',
	`itemId6` INT(11) NOT NULL DEFAULT '0',
	`itemId7` INT(11) NOT NULL DEFAULT '0',
	`itemId8` INT(11) NOT NULL DEFAULT '0',
	`itemId9` INT(11) NOT NULL DEFAULT '0',
	`itemId10` INT(11) NOT NULL DEFAULT '0',
	`itemId11` INT(11) NOT NULL DEFAULT '0',
	`itemId12` INT(11) NOT NULL DEFAULT '0',
	`itemId13` INT(11) NOT NULL DEFAULT '0',
	`itemId14` INT(11) NOT NULL DEFAULT '0',
	`itemId15` INT(11) NOT NULL DEFAULT '0',
	`itemId16` INT(11) NOT NULL DEFAULT '0',
	`itemId17` INT(11) NOT NULL DEFAULT '0',
	`itemId18` INT(11) NOT NULL DEFAULT '0',
	`itemId19` INT(11) NOT NULL DEFAULT '0',
	`itemId20` INT(11) NOT NULL DEFAULT '0',
	`itemId21` INT(11) NOT NULL DEFAULT '0',
	`itemId22` INT(11) NOT NULL DEFAULT '0',
	`itemId23` INT(11) NOT NULL DEFAULT '0',
	`itemId24` INT(11) NOT NULL DEFAULT '0',
	`displayInfo1` INT(11) NOT NULL DEFAULT '0',
	`displayInfo2` INT(11) NOT NULL DEFAULT '0',
	`displayInfo3` INT(11) NOT NULL DEFAULT '0',
	`displayInfo4` INT(11) NOT NULL DEFAULT '0',
	`displayInfo5` INT(11) NOT NULL DEFAULT '0',
	`displayInfo6` INT(11) NOT NULL DEFAULT '0',
	`displayInfo7` INT(11) NOT NULL DEFAULT '0',
	`displayInfo8` INT(11) NOT NULL DEFAULT '0',
	`displayInfo9` INT(11) NOT NULL DEFAULT '0',
	`displayInfo10` INT(11) NOT NULL DEFAULT '0',
	`displayInfo11` INT(11) NOT NULL DEFAULT '0',
	`displayInfo12` INT(11) NOT NULL DEFAULT '0',
	`displayInfo13` INT(11) NOT NULL DEFAULT '0',
	`displayInfo14` INT(11) NOT NULL DEFAULT '0',
	`displayInfo15` INT(11) NOT NULL DEFAULT '0',
	`displayInfo16` INT(11) NOT NULL DEFAULT '0',
	`displayInfo17` INT(11) NOT NULL DEFAULT '0',
	`displayInfo18` INT(11) NOT NULL DEFAULT '0',
	`displayInfo19` INT(11) NOT NULL DEFAULT '0',
	`displayInfo20` INT(11) NOT NULL DEFAULT '0',
	`displayInfo21` INT(11) NOT NULL DEFAULT '0',
	`displayInfo22` INT(11) NOT NULL DEFAULT '0',
	`displayInfo23` INT(11) NOT NULL DEFAULT '0',
	`displayInfo24` INT(11) NOT NULL DEFAULT '0',
	`invType1` INT(11) NOT NULL DEFAULT '0',
	`invType2` INT(11) NOT NULL DEFAULT '0',
	`invType3` INT(11) NOT NULL DEFAULT '0',
	`invType4` INT(11) NOT NULL DEFAULT '0',
	`invType5` INT(11) NOT NULL DEFAULT '0',
	`invType6` INT(11) NOT NULL DEFAULT '0',
	`invType7` INT(11) NOT NULL DEFAULT '0',
	`invType8` INT(11) NOT NULL DEFAULT '0',
	`invType9` INT(11) NOT NULL DEFAULT '0',
	`invType10` INT(11) NOT NULL DEFAULT '0',
	`invType11` INT(11) NOT NULL DEFAULT '0',
	`invType12` INT(11) NOT NULL DEFAULT '0',
	`invType13` INT(11) NOT NULL DEFAULT '0',
	`invType14` INT(11) NOT NULL DEFAULT '0',
	`invType15` INT(11) NOT NULL DEFAULT '0',
	`invType16` INT(11) NOT NULL DEFAULT '0',
	`invType17` INT(11) NOT NULL DEFAULT '0',
	`invType18` INT(11) NOT NULL DEFAULT '0',
	`invType19` INT(11) NOT NULL DEFAULT '0',
	`invType20` INT(11) NOT NULL DEFAULT '0',
	`invType21` INT(11) NOT NULL DEFAULT '0',
	`invType22` INT(11) NOT NULL DEFAULT '0',
	`invType23` INT(11) NOT NULL DEFAULT '0',
	`invType24` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `creaturedisplayinfo` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ModelID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`SoundID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ExtendedDisplayInfoID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`CreatureModelScale` FLOAT NOT NULL DEFAULT '0',
	`CreatureModelAlpha` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`TextureVariation_1` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`TextureVariation_2` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`TextureVariation_3` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`PortraitTextureName` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`BloodLevel` INT(11) NOT NULL DEFAULT '0',
	`BloodID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`NPCSoundID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ParticleColorID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`CreatureGeosetData` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ObjectEffectPackageID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `creaturedisplayinfoextra` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`DisplayRaceID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`DisplaySexID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`SkinID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`FaceID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`HairStyleID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`HairColorID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`FacialHairID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`HeadDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ShouldersDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ShirtDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ChestDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BeltDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`LegsDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BootsDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BracersDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`GlovesDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`TabardDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`CapeDisplayID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`BakedTextureIDblp` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `creaturemodeldata` (
	`id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`modelPath` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sizeClass` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`modelScale` FLOAT NOT NULL DEFAULT '0',
	`bloodId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`footprintTextureId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`footprintTextureLength` FLOAT NOT NULL DEFAULT '0',
	`footprintTextureWidth` FLOAT NOT NULL DEFAULT '0',
	`footprintParticleScale` FLOAT NOT NULL DEFAULT '0',
	`foleyMaterialId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`footstepShakeSize` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`deathThudShakeSize` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`soundData` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`collisionWidth` FLOAT NOT NULL DEFAULT '0',
	`collisionHeight` FLOAT NOT NULL DEFAULT '0',
	`mountHeight` FLOAT NOT NULL DEFAULT '0',
	`geoBoxMinX` FLOAT NOT NULL DEFAULT '0',
	`geoBoxMinY` FLOAT NOT NULL DEFAULT '0',
	`geoBoxMinZ` FLOAT NOT NULL DEFAULT '0',
	`geoBoxMaxX` FLOAT NOT NULL DEFAULT '0',
	`geoBoxMaxY` FLOAT NOT NULL DEFAULT '0',
	`geoBoxMaxZ` FLOAT NOT NULL DEFAULT '0',
	`worldEffectScale` FLOAT NOT NULL DEFAULT '0',
	`attachedEffectScale` FLOAT NOT NULL DEFAULT '0',
	`MissileCollisionRadius` FLOAT NOT NULL DEFAULT '0',
	`MissileCollisionPush` FLOAT NOT NULL DEFAULT '0',
	`MissileCollisionRaise` FLOAT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;
CREATE TABLE `currencycategory` (
	`id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`name1` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name2` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name3` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name4` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name5` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name6` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name7` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name8` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name9` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name10` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name11` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name12` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name13` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name14` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name15` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name16` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`nameFlags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `currencytypes` (
	`id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`item` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`category` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`bitIndex` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;

CREATE TABLE `custom_banned_spell_system` (
	`spellID` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `custom_fixgear` (
	`characterGUID` INT(11) NULL DEFAULT NULL,
	`itemEntry` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `custom_spell_system` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`spellID` INT(11) NOT NULL,
	`spellName` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`spellLevel` INT(11) NOT NULL,
	INDEX `id` (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2036
;

CREATE TABLE `custom_spell_system_categories` (
	`spellID` INT(11) NULL DEFAULT NULL,
	`category` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `custom_spell_system_category_choices` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`characterGUID` INT(11) NULL DEFAULT NULL,
	`level` INT(11) NULL DEFAULT NULL,
	INDEX `id` (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=42393
;

CREATE TABLE `custom_spell_system_choices` (
	`characterGUID` INT(11) NULL DEFAULT NULL,
	`level` INT(11) NULL DEFAULT NULL,
	`spellID1` INT(11) NULL DEFAULT NULL,
	`spellID2` INT(11) NULL DEFAULT NULL,
	`spellID3` INT(11) NULL DEFAULT NULL,
	`spellID4` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `custom_stat_system` (
	`charguid` INT(11) NULL DEFAULT NULL,
	`strength` INT(11) NULL DEFAULT NULL,
	`agility` INT(11) NULL DEFAULT NULL,
	`stamina` INT(11) NULL DEFAULT NULL,
	`intellect` INT(11) NULL DEFAULT NULL,
	`spirit` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `custom_update_spells` (
	`spellID` INT(11) NULL DEFAULT NULL,
	`description` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci'
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `dungeonencounter` (
	`ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`mapId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`difficulty` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`orderIndex` INT(11) NOT NULL DEFAULT '0',
	`bit` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`name1` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name2` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name3` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name4` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name5` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name6` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name7` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name8` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name9` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name10` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name11` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name12` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name13` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name14` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name15` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`name16` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`nameFlags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`iconId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
;
